site_name: LINUX.CN Archive
#docs_dir: content

theme:
  name: material
  language: zh
  icon:
      logo: material/linux
  font:
    text: Open Sans, Helvetica Neue, Roboto, sans-serif, serif
    code: Fira Mono, Fira Code, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  # - search
  - blog:
      # blog_dir: .
      blog_toc: true
      # categories: false
      categories_toc: true
      # archive_url_date_format: yyyy/MM
      archive_toc: true
      post_url_format: "{slug}" # "{file}"
      pagination_per_page: 10
  # - tags:
  #     tags_file: blog/tags.md
